version: '3.7'

services:
  flashsale-rmqnamesrv:
    image: foxiswho/rocketmq:4.8.0
    container_name: flashsale-rmqnamesrv
    ports:
      - 9876:9876
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh", "mqnamesrv" ]
    networks:
        flashsale:
          aliases:
            - flashsale-rmqnamesrv
            - rmqnamesrv

  flashsale-rmqbroker:
    image: foxiswho/rocketmq:4.8.0
    container_name: flashsale-rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh", "mqbroker", "-n", "flashsale-rmqnamesrv:9876" ]
    depends_on:
      - flashsale-rmqnamesrv
    networks:
      flashsale:
        aliases:
          - flashsale-rmqbroker
          - rmqbroker

  flashsale-rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: flashsale-rmqconsole
    ports:
      - 8080:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=flashsale-rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - flashsale-rmqnamesrv
    networks:
      flashsale:
        aliases:
          - flashsale-rmqconsole
          - rmqconsole

  flashsale-redis:
    image: redis:6-alpine
    container_name: flashsale-redis
    ports:
      - 6379:6379
    volumes:
      - flashsale-redis:/data
    networks:
      flashsale:
        aliases:
          - flashsale-redis

  flashsale-mysql:
    image: mysql:5.7
    container_name: flashsale-mysql
    ports:
      - 3306:3306
    volumes:
      - flashsale-mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flashsale
      MYSQL_USER: flashsale
      MYSQL_PASSWORD: flashsale
    networks:
      flashsale:
        aliases:
          - flashsale-mysql

networks:
  flashsale:
    name: flashsale
    driver: bridge

volumes:
  flashsale-redis:
  flashsale-mysql:
